### ISSUE TITLE
joinWithIntersects shall skip test if geometry type is not supported

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#175]
Background:
- https://github.com/opengeospatial/ets-wfs20/issues/164#issuecomment-680795719
- https://github.com/opengeospatial/ets-wfs20/issues/164#issuecomment-601830404

**Comment by keshav-nangare** [comment]
Fixed with #177 PR.

**Comment by iuriemaxim** [comment]
@dstenger The following service can be used to test unsupported join of point geometries:

https://inspire-staging.meteoromania.ro/WIGOS/WFS?Service=WFS&version=2.0.0&request=GetCapabilities

In the [staging version of the inspire ETF validator](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), checking the conformance class Download Service - Direct WFS that is using the TEAM Engine, is still providing the message:

OGC TEAM Engine reported a failed test: This test has triggered an unexpected Spatial Join condition. The Spatial Join test will need to be applied manually.

**Comment by iuriemaxim** [comment]
When testing in the INSPIRE Validator on staging version I get the same error:

![image](https://user-images.githubusercontent.com/20813598/95622408-1e916680-0a7c-11eb-9faa-f649ad595241.png)

Was the issue solved? Can you please test that the following URL indicated above is now passing the test joinWithInterects:

https://inspire-staging.meteoromania.ro/WIGOS/WFS?Service=WFS&version=2.0.0&request=GetCapabilities

**Comment by dstenger** [comment]
Yes, the problem has been solved. However, the solution has not been installed on any OGC environment, yet.

@keshav-nangare Can you please verify if the provided test service (https://github.com/opengeospatial/ets-wfs20/issues/175#issuecomment-706357637) now passes the joinWithInterects test?

**Comment by iuriemaxim** [comment]
Tested on staging environment of the INSPIRE validator and I confirm that the issue is not anymore present on staging https://github.com/inspire-eu-validation/community/issues/209 However on production environment the problem is not yet fixed. Can it be provided a deadline for moving this fix into production environment of the TeamEngine?
