### ISSUE TITLE
INSPIRE WFS service fails for Temporal and Spatial Filter

### ISSUE THREAD

**Issue by Ana-SGA** [opengeospatial/ets-wfs20#247]
Dear all,

could someone take a look at these WFS services that fail OGC test on INSPIRE Validator regarding Temporal and Spatilal Filter:

- the first one http://servisi.azo.hr/inspire/geos1/lcv/wfs?service=WFS&version=2.0.0&request=GetCapabilities and the report https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID85b62332-e4cb-4b74-bb70-0816ce5bfa2e and
- the second one http://servisi.azo.hr/inspire/geos1/ef/wfs?service=WFS&version=2.0.0&request=GetCapabilities and the report https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID401ea1d3-481b-4f23-9c4e-fa27b30d772f - this one fails for intersecting curves, but the data are points. Also, there is an error for creating envelope 

Can somebody please explain these errors?

**Comment by dstenger** [comment]
Thank you for reporting.

Can you please point out which tests you expect to be passed and which test do not have a understandable error message?

The error regarding `invalid Geometry Operand` might be related to issues #233 and #235 which are already fixed and will be installed on Beta environment (https://cite.ogc.org/te2/) soon.

**Comment by dstenger** [comment]
Unfortunately, I cannot comment about the error messages of the INSPIRE validator and the provided links do not return a report.

When checking the provided services with TEAM Engine instance of OGC (https://cite.ogc.org/teamengine/), following error messages are returned for spatial and temporal filter:

Spatial filter:
```
1. intersects Curve | java.lang.AssertionError: Unexpected HTTP status code. expected <br>[200] but found <br>[400]
2. invalid Geometry Operand | java.lang.RuntimeException: Could not create  envelope for feature type:  {http://inspire.ec.europa.eu/schemas/ef/4.0}ObservingCapability
3. intersects Polygon | java.lang.AssertionError: Unexpected HTTP status code. expected <br>[200] but found <br>[400]
```

Comment on failures:
1. Wrong HTTP status code is returned. It seems that your service throws an exception.
   * Following is tested: `Submits a GetFeature request containing an Intersects predicate with a gml:LineString or gml:Curve (LineStringSegment) operand. The response entity must be schema-valid and contain only matching instances.`
3. Is already fixed. Beta (https://cite.ogc.org/te2/) will be updated soon. Please see my previous comment.
4. Wrong HTTP status code is returned. It seems that your service throws an exception.
   * Following is tested: `Submits a GetFeature request containing an Intersects predicate with a gml:Polygon operand. The response entity must be schema-valid and contain only matching instances.`

Temporal filter:
```
1. after Instant | java.lang.AssertionError: Unexpected HTTP status code. expected <br>[200] but found <br>[400]
...
all following tests with the same failure message
```

Comment on failures:
1. Wrong HTTP status code is returned. It seems that your service throws an exception saying that temporal filters are not supported by the service.
   * However, the capabilities (http://servisi.azo.hr/inspire/geos1/lcv/wfs?service=WFS&version=2.0.0&request=GetCapabilities) state otherwise:
```
<fes:Constraint name="ImplementsTemporalFilter">
    <ows:NoValues/>
    <ows:DefaultValue>TRUE</ows:DefaultValue>
</fes:Constraint>
```

**Comment by Ana-SGA** [comment]
Dear @dstenger,
thanks a lot for commenting. I have attached reports from the INSPIRE Validator, seems that the errors are the same as with OGC validator. Concerning these errors (Spatial and Temporal Filter) we should fix them on our part, they aren't OGC Validators errors (except for the invalidGeometryOperand right? We really appreciate your help.
[ZA Github.zip](https://github.com/opengeospatial/ets-wfs20/files/10054593/ZA.Github.zip)

**Comment by dstenger** [comment]
@Ana-SGA It seems that all problems have been discussed and I propose to close the issue. Can you please confirm if that is fine for you?

**Comment by Ana-SGA** [comment]
Dear all, @dstenger,

we still get an error invalidGeometryOperand OGC TEAM Engine reported a failed test: Could not create envelope for feature type: {http://inspire.ec.europa.eu/schemas/tn-ra/4.0}RailwayElectrification for this service https://nipp.hzinfra.hr/geoserver/tn-ra/wfs?service=WFS&request=GetCapabilities&version=2.0.0.

Can someone take a look?

**Comment by dstenger** [comment]
@Ana-SGA

When I am running the provided service against Beta environment (https://cite.ogc.org/te2/) which contains the latest fixes, test invalidGeometryOperand passes.

On Production environment (https://cite.ogc.org/teamengine/) test invalidGeometryOperand fails with the provided service.

This is due to the case that the relevant fixes #233 and #235 are part of version 1.39 and 1.40 of the test suite.
Production, however, has version 1.38 installed (please see landing page of https://cite.ogc.org/teamengine/).
Thus, a failure on Production is expected.

An update of Production is planned for autumn. Then, the version currently installed on Beta will be moved to Production.

**Comment by JohannaOtt** [comment]
> for another service again we get error invalidGeometryOperand OGC TEAM Engine reported a failed test: Could not create envelope for feature type: {[http://inspire.ec.europa.eu/schemas/tn-ra/4.0}RailwayElectrification](http://inspire.ec.europa.eu/schemas/tn-ra/4.0%7DRailwayElectrification) for this service https://nipp.hzinfra.hr/geoserver/tn-ra/wfs?service=WFS&request=GetCapabilities&version=2.0.0.

I get the same type of error messages (different service, different type, but pattern is the same) when testing [this WFS](https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wfs?ACCEPTVERSIONS=2.0.0&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) in the beta instance using version 1.41 of the WFS 2.0 validator
![grafik](https://github.com/opengeospatial/ets-wfs20/assets/34163838/09a74055-b892-4863-94bb-94c8fc763237)

@dstenger Could you please take a look what is causing those?

**Comment by dstenger** [comment]
@JohannaOtt Thank you for reporting. I can reproduce the problem.
However, there are different tests affected in your case. Also, this issue is very generic and discusses multiple problems.
Thus, I propose to create a new issue for your problem.

@Ana-SGA As stated in comment https://github.com/opengeospatial/ets-wfs20/issues/247#issuecomment-1380072322, I propose to close this issue as all findings have been discussed. If there are no objections, I will close this issues in a couple of weeks.

**Comment by JohannaOtt** [comment]
> Thus, I propose to create a new issue for your problem.

Agreed, I created https://github.com/opengeospatial/ets-wfs20/issues/274 for it now.

**Comment by Ana-SGA** [comment]
Dear @dstenger,

we can close this issue. Thank you for helping.
